config/routes.rb
RedmineApp::Application.routes.draw do
  resources :projects do
    resources :auto_rules, only: [:index, :create, :destroy] do
      get :custom_field_values, on: :collection
    end
  end
end

app/models/auto_rule.rb
class AutoRule < ActiveRecord::Base
  belongs_to :project
  belongs_to :custom_field
  belongs_to :assignee, class_name: 'Principal', optional: true

  def watchers
    Principal.where(id: watcher_ids.to_s.split(',').map(&:to_i))
  end

  def watcher_ids_array
    watcher_ids.to_s.split(',').map(&:to_i)
  end

  def watcher_ids_array=(ids)
    self.watcher_ids = ids.reject(&:blank?).join(',')
  end
end

app/controllers/auto_rules_controller.rb
class AutoRulesController < ApplicationController
  before_action :find_project, :authorize, except: [:custom_field_values]
  before_action :authorize, only: [:index, :create, :destroy]
  skip_before_action :find_project, only: [:custom_field_values]

  def index
    @rules = @project.auto_rules
    @rule  = AutoRule.new
    @assignable_principals = @project.principals.sort_by(&:name)
  end

  def create
    @rule = @project.auto_rules.build(rule_params)
    if @rule.save
      flash[:notice] = "Rule created successfully"
    else
      flash[:error] = "Failed to create rule"
    end
    redirect_to project_auto_rules_path(@project)
  end

  def destroy
    @rule = @project.auto_rules.find(params[:id])
    @rule.destroy
    flash[:notice] = "Rule deleted"
    redirect_to project_auto_rules_path(@project)
  end

  def custom_field_values
    cf = CustomField.find(params[:id])

    if cf.field_format == 'enumeration'
      render json: cf.enumerations.map(&:name)
    elsif cf.field_format == 'list'
      render json: cf.possible_values
    elsif cf.field_format == 'bool'
      render json: [true, false]
    else
      render json: []
    end
  rescue ActiveRecord::RecordNotFound
    render json: []
  end

  private

  def rule_params
    params.require(:auto_rule).permit(:custom_field_id, :custom_field_value, :assignee_id, watcher_ids_array: [])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/views/auto_rules/_form.html.erb
<p>
  <%= f.label :custom_field_id, "Custom Field" %><br>
  <%= f.collection_select :custom_field_id,
        CustomField.where(type: "IssueCustomField"),
        :id, :name,
        { include_blank: true },
        { id: "custom_field_select" } %>
</p>

<p>
  <%= f.label :custom_field_value, "Custom Field Value" %><br>
  <%= f.select :custom_field_value,
        [],
        { include_blank: true },
        { id: "custom_field_value_select" } %>
</p>

app/views/auto_rules/index.html.erb
<h2>Auto Rules</h2>

<%= form_with model: [@project, @rule], local: true do |f| %>
  <p>
    <%= f.label :custom_field_id, "Custom Field" %><br>
    <%= f.collection_select :custom_field_id,
        CustomField.where(type: "IssueCustomField"),
        :id, :name,
        { include_blank: true },
        { id: "custom_field_select" } %>
  </p>

  <p>
    <%= f.label :custom_field_value, "Custom Field Value" %><br>
    <%= f.select :custom_field_value, [], { include_blank: true }, { id: "custom_field_value_select" } %>
  </p>

  <p>
    <%= f.label :assignee_id, "Assignee" %><br>
    <%= f.collection_select :assignee_id,
        @assignable_principals,
        :id, :name,
        { include_blank: true } %>
  </p>

  <p>
    <%= f.label :watcher_ids_array, "Watchers" %><br>
    <% @assignable_principals.each do |principal| %>
      <label>
        <%= check_box_tag "auto_rule[watcher_ids_array][]", principal.id, @rule.watcher_ids_array.include?(principal.id) %>
        <%= principal.name %>
      </label><br>
    <% end %>
  </p>

  <%= f.submit "Add Rule" %>
<% end %>

<hr>

<h3>Existing Rules</h3>
<table class="list">
  <thead>
    <tr>
      <th>Custom Field</th>
      <th>Value</th>
      <th>Assignee</th>
      <th>Watchers</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.custom_field.try(:name) %></td>
        <td><%= rule.custom_field_value %></td>
        <td><%= rule.assignee.try(:name) %></td>
        <td><%= rule.watchers.map(&:name).join(", ") %></td>
        <td>
          <%= link_to "Delete", project_auto_rule_path(@project, rule),
                method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
document.getElementById("custom_field_select").addEventListener("change", function() {
  var fieldId = this.value;
  var select = document.getElementById("custom_field_value_select");

  if (!fieldId) {
    select.innerHTML = "<option value=''></option>";
    return;
  }

  // Use the correct nested route helper name with the project ID
  fetch("<%= custom_field_values_project_auto_rules_path(@project) %>" + "?id=" + fieldId)
    .then(response => {
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      return response.json();
    })
    .then(data => {
      select.innerHTML = "<option value=''></option>";
      data.forEach(function(option) {
        var opt = document.createElement("option");
        opt.value = option;
        opt.textContent = option;
        select.appendChild(opt);
      });
    })
    .catch(error => {
      console.error('Fetch error:', error);
    });
});
</script>